FROM nginx:stable

RUN rm /etc/nginx/conf.d/default.conf
COPY config/httpd_default.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY index.css /usr/share/nginx/html
