version: "3.8"
services:
  httpd:
    build:
      context: .
      target: httpd
    networks:
      default:
        aliases:
          - httpd
    ports:
      - "8080:80"
    tty: true
    depends_on:
       - rucs_api
#    volumes: 
#      - ./conf/httpd_default.conf:/etc/nginx/conf.d/default.conf:ro
      
  rucs_api:
    build:
       context: .
       target: rucs_api
    depends_on:
      - rucs_db
    environment:
      - DEMO=${RUCS_DEMO}
      - PRODUCTION_CONFIG=${RUCS_PRODUCTION_CONFIG}
    networks:
      default:
        aliases:
          - rucs_api
    tty: true
#    volumes:
#      - .:/pyap1

  rucs_db:
#    build:
#      context: .
#      target: rucs_db
    image: mongo:4.0.20-xenial
    networks:
      default:
        aliases:
          - rucs_db
    tty: true
