version: "3.8"
services:
  httpd:
    build:
      context: ./config
      dockerfile: Dockerfile-httpd
    image: httpd:rucs-nginx-http-server
    networks:
      default:
        aliases:
          - httpd
    ports:
      - "8080:80"
    tty: true
    depends_on:
       - rucs_api
#    volumes: 
#      - ./conf/httpd_default.conf:/etc/nginx/conf.d/default.conf:ro
      
  rucs_api:
    build:
       context: .
       target: rucs_api
    image: rucs-api:rucs-api
    depends_on:
      - rucs_db
    environment:
      - DEMO=${RUCS_DEMO}
      - PRODUCTION_CONFIG=${RUCS_PRODUCTION_CONFIG}
    networks:
      default:
        aliases:
          - rucs_api
    tty: true
    volumes:
      - .:/usr/src
      - rucs-api-pybits:/usr/lib/__pycache__
      - rucs-api-instance:/usr/lib/rucs-api-instance

  rucs_db:
    image: mongo:4.0.20-xenial
    networks:
      default:
        aliases:
          - rucs_db
    tty: true
