version: "3.8"
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile-httpd
    depends_on:
       - rucs_api
    image: httpd:rucs-nginx-http-server
    networks:
      default:
        aliases:
          - httpd
    ports:
      - "8080:80"
    tty: true
    volumes:
       - ./httpd/content:/usr/share/nginx/html:ro

  rucs_api:
    build:
       context: .
    depends_on:
      - rucs_db
    environment:
      - DEMO=${RUCS_DEMO}
      - PRODUCTION_CONFIG=${RUCS_PRODUCTION_CONFIG}
    image: rucs-api:rucs-api
    networks:
      default:
        aliases:
          - rucs_api
    tty: true
    volumes:
      - .:/usr/src:ro
      - rucs-api-pybits:/usr/lib/__pycache__
      - rucs-api-instance:/usr/lib/rucs-api-instance

  rucs_db:
    image: mongo:4.0.20-xenial
    networks:
      default:
        aliases:
          - rucs_db
    tty: true

volumes:
  rucs-api-instance:
  rucs-api-pybits:
