#!/bin/bash
# - execute uwsgi server for RUCS
# - initialization of a development / demo house state Mongodb
# collection
#
# todo: if PRODUCTION_CONFIG is set, there is no need
# to initialize the dev database

# if DEMO is set in the env (used in docker-compose.yml)
# define DEMO=set. If PRODUCTION_CONFIG is set (used in
# docker-compose.yml), read
# production settings (such as secret key) from PRODUCTION_CONFIG
# variable, otherwise, read from file dev.cfg
mkdir /usr/lib/__pycache__
export PYTHONPYCACHEPREFIX=/usr/lib/__pycache__
chown 1000:1000 instance/rucs.log
chown 1000:1000 instance/dev.cfg
python demo/demo_house_state.py \
	&&
	DEMO=${DEMO:+bar} \
	BYPASS_AUTH=${BYPASS_AUTH+baz} \
	RUCS_CONFIG=${PRODUCTION_CONFIG:-dev.cfg} \
	uwsgi \
		--socket rucs_api:3031 \
		--manage-script-name \
		--mount '/=rucs:create_app()' \
		--master \
		--processes 4 \
		--threads 2 \
